version: '3'
services:
  nginx:
    container_name: 'nginx'
    restart: always
    build: ./nginx
    ports:
      - "8080:80"
    depends_on: 
      - mysql
      - app
  mysql:
    restart: on-failure
    image: mysql:5.7
    container_name: 'database'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    container_name: 'app'
    restart: on-failure
    build: ./app
    depends_on:
      - mysql
    volumes:
      - ./app:/usr/src/app
